import "./globals.css";
import "@/components/LexicalEditor/lexical.css";
import "@/components/LexicalEditor/themes/CommentEditorTheme";
import "@/components/LexicalEditor/themes/PlaygroundEditorTheme.css";
import "@/components/LexicalEditor/themes/StickyEditorTheme";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-full bg-white">
      <body className={`${inter.className} h-full`}>
        {children}
        <Toaster />
      </body>
    </html>
  );
}
