export * from "./ClinicalEvent/args";
export * from "./Consultation/args";
export * from "./ConsultationList/args";
export * from "./DocumentTemplate/args";
export * from "./MobileDevice/args";
export * from "./Patient/args";
export * from "./Prescription/args";
export * from "./Setting/args";
export * from "./User/args";
