export const lexicalStyles = {
  header: {
    maxWidth: "580px",
    margin: "auto",
    position: "relative",
    display: "flex",
    justifyContent: "center",
  },
  header_a: { maxWidth: "220px", margin: "20px 0 0 0", display: "block" },
  header_img: { display: "block", height: "100%", width: "100%" },
  header_h1: {
    textAlign: "left",
    color: "#333",
    display: "inline-block",
    margin: "20px 0 0 0",
  },
  editor_shell: {
    margin: "20px auto",
    color: "#000",
    position: "relative",
    lineHeight: "1.7",
    fontWeight: "400",
  },
  editor_shell__editor_container: {
    background: "#fff",
    position: "relative",
    display: "block",
    borderBottomLeftRadius: "10px",
    borderBottomRightRadius: "10px",
  },
  editor_shell__editor_container_tree_view: { borderRadius: "0" },
  editor_shell__editor_container_plain_text: {
    borderTopLeftRadius: "10px",
    borderTopRightRadius: "10px",
  },
  editor_scroller: {
    minHeight: "150px",
    border: "0",
    display: "flex",
    position: "relative",
    outline: "0",
    zIndex: "0",
    overflow: "auto",
    resize: "vertical",
  },
  editor: {
    flex: "auto",
    position: "relative",
    resize: "vertical",
    zIndex: "-1",
  },
  test_recorder_output: { margin: "20px auto 20px auto", width: "100%" },
  pre: {
    lineHeight: "1.1",
    background: "#222",
    color: "#fff",
    margin: "0",
    padding: "10px",
    fontSize: "12px",
    overflow: "auto",
    maxHeight: "400px",
  },
  tree_view_output: {
    display: "block",
    background: "#222",
    color: "#fff",
    padding: "0",
    fontSize: "12px",
    margin: "1px auto 10px auto",
    position: "relative",
    overflow: "hidden",
    borderBottomLeftRadius: "10px",
    borderBottomRightRadius: "10px",
  },
  pre___webkit_scrollbar: { background: "transparent", width: "10px" },
  pre___webkit_scrollbar_thumb: { background: "#999" },
  editor_dev_button: {
    position: "relative",
    display: "block",
    width: "40px",
    height: "40px",
    fontSize: "12px",
    borderRadius: "20px",
    border: "none",
    cursor: "pointer",
    outline: "none",
    boxShadow: "0px 1px 10px rgba(0, 0, 0, 0.3)",
    backgroundColor: "#444",
  },
  editor_dev_button__after: {
    content: "''",
    position: "absolute",
    top: "10px",
    right: "10px",
    bottom: "10px",
    left: "10px",
    display: "block",
    backgroundSize: "contain",
    filter: "invert(1)",
  },
  editor_dev_button_hover: { backgroundColor: "#555" },
  editor_dev_button_active: { backgroundColor: "rgb(233, 35, 35)" },
  test_recorder_toolbar: { display: "flex" },
  test_recorder_button: { position: "fixed", left: "70px", bottom: "20px" },
  test_recorder_button_active: { boxShadow: "1px 2px 4px rgba(0, 0, 0, 0.4)" },
  test_recorder_button____test_recorder_button: { marginLeft: "4px" },
  test_recorder_button__after: {
    backgroundImage: "url(images/icons/journal-code.svg)",
  },
  options_button: { position: "fixed", left: "20px", bottom: "20px" },
  paste_log_button: { position: "fixed", left: "120px", bottom: "20px" },
  docs_button: { position: "fixed", left: "170px", bottom: "20px" },
  options_button__after: { backgroundImage: "url(images/icons/gear.svg)" },
  paste_log_button__after: {
    backgroundImage: "url(images/icons/clipboard.svg)",
  },
  docs_button__after: {
    backgroundImage: "url(images/icons/file-earmark-text.svg)",
  },
  test_recorder_button_snapshot: { marginRight: "auto" },
  test_recorder_button_snapshot__after: {
    backgroundImage: "url(images/icons/camera.svg)",
  },
  test_recorder_button_copy__after: {
    backgroundImage: "url(images/icons/clipboard.svg)",
  },
  test_recorder_button_download__after: {
    backgroundImage: "url(images/icons/download.svg)",
  },
  typeahead_popover: {
    background: "#fff",
    boxShadow: "0px 5px 10px rgba(0, 0, 0, 0.3)",
    borderRadius: "8px",
    marginTop: "25px",
  },
  typeahead_popover_ul: { MsOverflowStyle: "none", scrollbarWidth: "none" },
  typeahead_popover_ul___webkit_scrollbar: { display: "none" },
  typeahead_popover_ul_li: {
    margin: "0",
    minWidth: "180px",
    fontSize: "14px",
    outline: "none",
    cursor: "pointer",
    borderRadius: "8px",
  },
  typeahead_popover_ul_li_selected: { background: "#eee" },
  typeahead_popover_li: {
    margin: "0 8px 0 8px",
    padding: "8px",
    color: "#050505",
    cursor: "pointer",
    lineHeight: "16px",
    fontSize: "15px",
    display: "flex",
    alignContent: "center",
    flexDirection: "row",
    flexShrink: "0",
    backgroundColor: "#fff",
    borderRadius: "8px",
    border: "0",
  },
  typeahead_popover_li_active: {
    display: "flex",
    width: "20px",
    height: "20px",
    backgroundSize: "contain",
  },
  typeahead_popover_li_first_child: { borderRadius: "8px 8px 0px 0px" },
  typeahead_popover_li_last_child: { borderRadius: "0px 0px 8px 8px" },
  typeahead_popover_li_hover: { backgroundColor: "#eee" },
  typeahead_popover_li__text: {
    display: "flex",
    lineHeight: "20px",
    flexGrow: "1",
    minWidth: "150px",
  },
  typeahead_popover_li__icon: {
    display: "flex",
    width: "20px",
    height: "20px",
    userSelect: "none",
    marginRight: "8px",
    lineHeight: "16px",
    backgroundSize: "contain",
    backgroundRepeat: "no-repeat",
    backgroundPosition: "center",
  },
  component_picker_menu: { width: "200px" },
  mentions_menu: { width: "400px" },
  auto_embed_menu: { width: "150px" },
  emoji_menu: { width: "200px" },
  i_palette: { backgroundImage: "url(images/icons/palette.svg)" },
  i_bucket: { backgroundImage: "url(images/icons/paint-bucket.svg)" },
  i_bold: { backgroundImage: "url(images/icons/type-bold.svg)" },
  i_italic: { backgroundImage: "url(images/icons/type-italic.svg)" },
  i_clear: { backgroundImage: "url(images/icons/trash.svg)" },
  i_code: { backgroundImage: "url(images/icons/code.svg)" },
  i_underline: { backgroundImage: "url(images/icons/type-underline.svg)" },
  i_strikethrough: {
    backgroundImage: "url(images/icons/type-strikethrough.svg)",
  },
  i_subscript: { backgroundImage: "url(images/icons/type-subscript.svg)" },
  i_superscript: { backgroundImage: "url(images/icons/type-superscript.svg)" },
  i_link: { backgroundImage: "url(images/icons/link.svg)" },
  i_horizontal_rule: {
    backgroundImage: "url(images/icons/horizontal-rule.svg)",
  },
  icon_plus: { backgroundImage: "url(images/icons/plus.svg)" },
  icon_caret_right: {
    backgroundImage: "url(images/icons/caret-right-fill.svg)",
  },
  icon_dropdown_more: {
    backgroundImage: "url(images/icons/dropdown-more.svg)",
  },
  icon_font_color: { backgroundImage: "url(images/icons/font-color.svg)" },
  icon_font_family: { backgroundImage: "url(images/icons/font-family.svg)" },
  icon_bg_color: { backgroundImage: "url(images/icons/bg-color.svg)" },
  icon_table: {
    backgroundColor: "#6c757d",
    maskImage: "url(images/icons/table.svg)",
    WebkitMaskImage: "url(images/icons/table.svg)",
    maskRepeat: "no-repeat",
    WebkitMaskRepeat: "no-repeat",
    maskSize: "contain",
    WebkitMaskSize: "contain",
  },
  i_image: { backgroundImage: "url(images/icons/file-image.svg)" },
  i_table: { backgroundImage: "url(images/icons/table.svg)" },
  i_close: { backgroundImage: "url(images/icons/close.svg)" },
  i_figma: { backgroundImage: "url(images/icons/figma.svg)" },
  i_poll: { backgroundImage: "url(images/icons/card-checklist.svg)" },
  i_columns: { backgroundImage: "url(images/icons/3-columns.svg)" },
  i_tweet: { backgroundImage: "url(images/icons/tweet.svg)" },
  i_youtube: { backgroundImage: "url(images/icons/youtube.svg)" },
  icon_left_align: { backgroundImage: "url(images/icons/text-left.svg)" },
  i_left_align: { backgroundImage: "url(images/icons/text-left.svg)" },
  icon_center_align: { backgroundImage: "url(images/icons/text-center.svg)" },
  i_center_align: { backgroundImage: "url(images/icons/text-center.svg)" },
  icon_right_align: { backgroundImage: "url(images/icons/text-right.svg)" },
  i_right_align: { backgroundImage: "url(images/icons/text-right.svg)" },
  icon_justify_align: { backgroundImage: "url(images/icons/justify.svg)" },
  i_justify_align: { backgroundImage: "url(images/icons/justify.svg)" },
  i_indent: { backgroundImage: "url(images/icons/indent.svg)" },
  i_markdown: { backgroundImage: "url(images/icons/markdown.svg)" },
  i_outdent: { backgroundImage: "url(images/icons/outdent.svg)" },
  i_undo: { backgroundImage: "url(images/icons/arrow-counterclockwise.svg)" },
  i_redo: { backgroundImage: "url(images/icons/arrow-clockwise.svg)" },
  i_sticky: { backgroundImage: "url(images/icons/sticky.svg)" },
  i_mic: { backgroundImage: "url(images/icons/mic.svg)" },
  i_import: { backgroundImage: "url(images/icons/upload.svg)" },
  i_export: { backgroundImage: "url(images/icons/download.svg)" },
  i_diagram_2: { backgroundImage: "url(images/icons/diagram-2.svg)" },
  i_user: { backgroundImage: "url(images/icons/user.svg)" },
  i_equation: { backgroundImage: "url(images/icons/plus-slash-minus.svg)" },
  i_gif: { backgroundImage: "url(images/icons/filetype-gif.svg)" },
  i_copy: { backgroundImage: "url(images/icons/copy.svg)" },
  i_success: { backgroundImage: "url(images/icons/success.svg)" },
  i_prettier: { backgroundImage: "url(images/icons/prettier.svg)" },
  i_prettier_error: { backgroundImage: "url(images/icons/prettier-error.svg)" },
  i_page_break: { backgroundImage: "url(images/icons/scissors.svg)" },
  icon_page_break: { backgroundImage: "url(images/icons/scissors.svg)" },
  link_editor__button_active: { backgroundColor: "rgb(223, 232, 250)" },
  toolbar__button_active: { backgroundColor: "rgb(223, 232, 250)" },
  link_editor__link_input: {
    display: "block",
    width: "calc(100% - 75px)",
    boxSizing: "border-box",
    margin: "12px 12px",
    padding: "8px 12px",
    borderRadius: "15px",
    backgroundColor: "#eee",
    fontSize: "15px",
    color: "rgb(5, 5, 5)",
    border: "0",
    outline: "0",
    position: "relative",
    fontFamily: "inherit",
  },
  link_editor__link_view: {
    display: "block",
    width: "calc(100% - 24px)",
    margin: "8px 12px",
    padding: "8px 12px",
    borderRadius: "15px",
    fontSize: "15px",
    color: "rgb(5, 5, 5)",
    border: "0",
    outline: "0",
    position: "relative",
    fontFamily: "inherit",
  },
  link_editor__link_view_a: {
    display: "block",
    wordBreak: "break-word",
    width: "calc(100% - 33px)",
  },
  link_editor_div_link_edit: {
    backgroundImage: "url(images/icons/pencil-fill.svg)",
    backgroundSize: "16px",
    backgroundPosition: "center",
    backgroundRepeat: "no-repeat",
    width: "35px",
    verticalAlign: "-0.25em",
    position: "absolute",
    right: "30px",
    top: "0",
    bottom: "0",
    cursor: "pointer",
  },
  link_editor_div_link_trash: {
    backgroundImage: "url(images/icons/trash.svg)",
    backgroundSize: "16px",
    backgroundPosition: "center",
    backgroundRepeat: "no-repeat",
    width: "35px",
    verticalAlign: "-0.25em",
    position: "absolute",
    right: "0",
    top: "0",
    bottom: "0",
    cursor: "pointer",
  },
  link_editor_div_link_cancel: {
    backgroundImage: "url(images/icons/close.svg)",
    backgroundSize: "16px",
    backgroundPosition: "center",
    backgroundRepeat: "no-repeat",
    width: "35px",
    verticalAlign: "-0.25em",
    marginRight: "28px",
    position: "absolute",
    right: "0",
    top: "0",
    bottom: "0",
    cursor: "pointer",
  },
  link_editor_div_link_confirm: {
    backgroundImage: "url(images/icons/success-alt.svg)",
    backgroundSize: "16px",
    backgroundPosition: "center",
    backgroundRepeat: "no-repeat",
    width: "35px",
    verticalAlign: "-0.25em",
    marginRight: "2px",
    position: "absolute",
    right: "0",
    top: "0",
    bottom: "0",
    cursor: "pointer",
  },
  link_editor__link_input_a: {
    color: "rgb(33, 111, 219)",
    textDecoration: "underline",
    whiteSpace: "nowrap",
    overflow: "hidden",
    marginRight: "30px",
    textOverflow: "ellipsis",
  },
  link_editor__link_input_a_hover: { textDecoration: "underline" },
  link_editor__font_size_wrapper: { display: "flex", margin: "0 4px" },
  link_editor__font_family_wrapper: { display: "flex", margin: "0 4px" },
  link_editor_select: {
    padding: "6px",
    border: "none",
    backgroundColor: "rgba(0, 0, 0, 0.075)",
    borderRadius: "4px",
  },
  mention_focus: {
    boxShadow: "rgb(180 213 255) 0px 0px 0px 2px",
    outline: "none",
  },
  characters_limit: {
    color: "#888",
    fontSize: "12px",
    textAlign: "right",
    display: "block",
    position: "absolute",
    left: "12px",
    bottom: "5px",
  },
  characters_limit_characters_limit_exceeded: { color: "red" },
  dropdown: {
    zIndex: "100",
    display: "block",
    position: "fixed",
    boxShadow:
      "0 12px 28px 0 rgba(0, 0, 0, 0.2), 0 2px 4px 0 rgba(0, 0, 0, 0.1),\n    inset 0 0 0 1px rgba(255, 255, 255, 0.5)",
    borderRadius: "8px",
    minHeight: "40px",
    backgroundColor: "#fff",
  },
  dropdown__item: {
    margin: "0 8px 0 8px",
    padding: "8px",
    color: "#050505",
    cursor: "pointer",
    lineHeight: "16px",
    fontSize: "15px",
    display: "flex",
    alignContent: "center",
    flexDirection: "row",
    flexShrink: "0",
    justifyContent: "space-between",
    backgroundColor: "#fff",
    borderRadius: "8px",
    border: "0",
    maxWidth: "250px",
    minWidth: "100px",
  },
  dropdown__item_fontsize_item: { minWidth: "unset" },
  dropdown__item_fontsize_item__text: { minWidth: "unset" },
  dropdown__item__active: {
    display: "flex",
    width: "20px",
    height: "20px",
    backgroundSize: "contain",
  },
  dropdown__item_first_child: { marginTop: "8px" },
  dropdown__item_last_child: { marginBottom: "8px" },
  dropdown__item_hover: { backgroundColor: "#eee" },
  dropdown__item__text: {
    display: "flex",
    lineHeight: "20px",
    flexGrow: "1",
    minWidth: "150px",
  },
  dropdown__item__icon: {
    display: "flex",
    width: "20px",
    height: "20px",
    userSelect: "none",
    marginRight: "12px",
    lineHeight: "16px",
    backgroundSize: "contain",
    backgroundPosition: "center",
    backgroundRepeat: "no-repeat",
  },
  dropdown__divider: {
    width: "auto",
    backgroundColor: "#eee",
    margin: "4px 8px",
    height: "1px",
  },
  "@media screen and (max-width: 1100px)": {
    __expression__: "screen and (max-width: 1100px)",
    dropdown_button_text: { display: "none !important" },
    font_size__dropdown_button_text: { display: "flex !important" },
    code_language__dropdown_button_text: { display: "flex !important" },
  },
  icon_paragraph: { backgroundImage: "url(images/icons/text-paragraph.svg)" },
  icon_h1: { backgroundImage: "url(images/icons/type-h1.svg)" },
  icon_h2: { backgroundImage: "url(images/icons/type-h2.svg)" },
  icon_h3: { backgroundImage: "url(images/icons/type-h3.svg)" },
  icon_h4: { backgroundImage: "url(images/icons/type-h4.svg)" },
  icon_h5: { backgroundImage: "url(images/icons/type-h5.svg)" },
  icon_h6: { backgroundImage: "url(images/icons/type-h6.svg)" },
  icon_bullet_list: { backgroundImage: "url(images/icons/list-ul.svg)" },
  icon_bullet: { backgroundImage: "url(images/icons/list-ul.svg)" },
  icon_check_list: { backgroundImage: "url(images/icons/square-check.svg)" },
  icon_check: { backgroundImage: "url(images/icons/square-check.svg)" },
  icon_numbered_list: { backgroundImage: "url(images/icons/list-ol.svg)" },
  icon_number: { backgroundImage: "url(images/icons/list-ol.svg)" },
  icon_quote: { backgroundImage: "url(images/icons/chat-square-quote.svg)" },
  icon_code: { backgroundImage: "url(images/icons/code.svg)" },
  switches: {
    zIndex: "6",
    position: "fixed",
    left: "10px",
    bottom: "70px",
    animation: "slide-in 0.4s ease",
  },
  switch: {
    display: "block",
    color: "#444",
    margin: "5px 0",
    backgroundColor: "rgba(238, 238, 238, 0.7)",
    padding: "5px 10px",
    borderRadius: "10px",
  },
  rich_text_switch: { right: "0" },
  character_count_switch: { right: "130px" },
  switch_label: {
    marginRight: "5px",
    lineHeight: "24px",
    width: "100px",
    fontSize: "14px",
    display: "inline-block",
    verticalAlign: "middle",
  },
  switch_button: {
    backgroundColor: "rgb(206, 208, 212)",
    height: "24px",
    boxSizing: "border-box",
    borderRadius: "12px",
    width: "44px",
    display: "inline-block",
    verticalAlign: "middle",
    position: "relative",
    outline: "none",
    cursor: "pointer",
    transition: "background-color 0.1s",
    border: "2px solid transparent",
  },
  switch_button_focus_visible: { borderColor: "blue" },
  switch_button_span: {
    top: "0px",
    left: "0px",
    display: "block",
    position: "absolute",
    width: "20px",
    height: "20px",
    borderRadius: "12px",
    backgroundColor: "white",
    transition: "transform 0.2s",
  },
  switch_button_aria_checked__true: { backgroundColor: "rgb(24, 119, 242)" },
  switch_button_aria_checked__true___span: { transform: "translateX(20px)" },
  editor_shell_span_editor_image: {
    cursor: "default",
    display: "inline-block",
    position: "relative",
    userSelect: "none",
  },
  editor_shell__editor_image_img: { maxWidth: "100%", cursor: "default" },
  editor_shell__editor_image_img_focused: {
    outline: "2px solid rgb(60, 132, 244)",
    userSelect: "none",
  },
  editor_shell__editor_image_img_focused_draggable: { cursor: "grab" },
  editor_shell__editor_image_img_focused_draggable_active: {
    cursor: "grabbing",
  },
  editor_shell__editor_image__image_caption_container__tree_view_output: {
    margin: "0",
    borderRadius: "0",
  },
  editor_shell__editor_image__image_caption_container: {
    display: "block",
    position: "absolute",
    bottom: "4px",
    left: "0",
    right: "0",
    padding: "0",
    margin: "0",
    borderTop: "1px solid #fff",
    backgroundColor: "rgba(255, 255, 255, 0.9)",
    minWidth: "100px",
    color: "#000",
    overflow: "hidden",
  },
  editor_shell__editor_image__image_caption_button: {
    display: "block",
    position: "absolute",
    bottom: "20px",
    left: "0",
    right: "0",
    width: "30%",
    padding: "10px",
    margin: "0 auto",
    border: "1px solid rgba(255, 255, 255, 0.3)",
    borderRadius: "5px",
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    minWidth: "100px",
    color: "#fff",
    cursor: "pointer",
    userSelect: "none",
  },
  editor_shell__editor_image__image_caption_button_hover: {
    backgroundColor: "rgba(60, 132, 244, 0.5)",
  },
  editor_shell__editor_image__image_edit_button: {
    border: "1px solid rgba(0, 0, 0, 0.3)",
    borderRadius: "5px",
    backgroundImage: "url(/src/images/icons/pencil-fill.svg)",
    backgroundSize: "16px",
    backgroundPosition: "center",
    backgroundRepeat: "no-repeat",
    width: "35px",
    height: "35px",
    verticalAlign: "-0.25em",
    position: "absolute",
    right: "4px",
    top: "4px",
    cursor: "pointer",
    userSelect: "none",
  },
  editor_shell__editor_image__image_edit_button_hover: {
    backgroundColor: "rgba(60, 132, 244, 0.1)",
  },
  editor_shell__editor_image__image_resizer: {
    display: "block",
    width: "7px",
    height: "7px",
    position: "absolute",
    backgroundColor: "rgb(60, 132, 244)",
    border: "1px solid #fff",
  },
  editor_shell__editor_image__image_resizer_image_resizer_n: {
    top: "-6px",
    left: "48%",
    cursor: "n-resize",
  },
  editor_shell__editor_image__image_resizer_image_resizer_ne: {
    top: "-6px",
    right: "-6px",
    cursor: "ne-resize",
  },
  editor_shell__editor_image__image_resizer_image_resizer_e: {
    bottom: "48%",
    right: "-6px",
    cursor: "e-resize",
  },
  editor_shell__editor_image__image_resizer_image_resizer_se: {
    bottom: "-2px",
    right: "-6px",
    cursor: "nwse-resize",
  },
  editor_shell__editor_image__image_resizer_image_resizer_s: {
    bottom: "-2px",
    left: "48%",
    cursor: "s-resize",
  },
  editor_shell__editor_image__image_resizer_image_resizer_sw: {
    bottom: "-2px",
    left: "-6px",
    cursor: "sw-resize",
  },
  editor_shell__editor_image__image_resizer_image_resizer_w: {
    bottom: "48%",
    left: "-6px",
    cursor: "w-resize",
  },
  editor_shell__editor_image__image_resizer_image_resizer_nw: {
    top: "-6px",
    left: "-6px",
    cursor: "nw-resize",
  },
  editor_shell_span_inline_editor_image: {
    cursor: "default",
    display: "inline-block",
    position: "relative",
    zIndex: "1",
  },
  editor_shell__inline_editor_image_img: {
    maxWidth: "100%",
    cursor: "default",
  },
  editor_shell__inline_editor_image_img_focused: {
    outline: "2px solid rgb(60, 132, 244)",
  },
  editor_shell__inline_editor_image_img_focused_draggable: { cursor: "grab" },
  editor_shell__inline_editor_image_img_focused_draggable_active: {
    cursor: "grabbing",
  },
  editor_shell__inline_editor_image__image_caption_container__tree_view_output:
    { margin: "0", borderRadius: "0" },
  editor_shell__inline_editor_image_position_full: { margin: "1em 0 1em 0" },
  editor_shell__inline_editor_image_position_left: {
    float: "left",
    width: "50%",
    margin: "1em 1em 0 0",
  },
  editor_shell__inline_editor_image_position_right: {
    float: "right",
    width: "50%",
    margin: "1em 0 0 1em",
  },
  editor_shell__inline_editor_image__image_edit_button: {
    display: "block",
    position: "absolute",
    top: "12px",
    right: "12px",
    padding: "6px 8px",
    margin: "0 auto",
    border: "1px solid rgba(255, 255, 255, 0.3)",
    borderRadius: "5px",
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    minWidth: "60px",
    color: "#fff",
    cursor: "pointer",
    userSelect: "none",
  },
  editor_shell__inline_editor_image__image_edit_button_hover: {
    backgroundColor: "rgba(60, 132, 244, 0.5)",
  },
  editor_shell__inline_editor_image__image_caption_container: {
    display: "block",
    backgroundColor: "#f4f4f4",
    minWidth: "100%",
    color: "#000",
    overflow: "hidden",
  },
  emoji: {
    color: "transparent",
    caretColor: "rgb(5, 5, 5)",
    backgroundSize: "16px 16px",
    backgroundPosition: "center",
    backgroundRepeat: "no-repeat",
    verticalAlign: "middle",
    margin: "0 -1px",
  },
  emoji_inner: { padding: "0 0.15em" },
  emoji_inner__selection: {
    color: "transparent",
    backgroundColor: "rgba(150, 150, 150, 0.4)",
  },
  emoji_inner__moz_selection: {
    color: "transparent",
    backgroundColor: "rgba(150, 150, 150, 0.4)",
  },
  emoji_happysmile: { backgroundImage: "url(images/emoji/1F642.png)" },
  emoji_veryhappysmile: { backgroundImage: "url(images/emoji/1F600.png)" },
  emoji_unhappysmile: { backgroundImage: "url(images/emoji/1F641.png)" },
  emoji_heart: { backgroundImage: "url(images/emoji/2764.png)" },
  keyword: { color: "rgb(241, 118, 94)", fontWeight: "bold" },
  actions: {
    position: "absolute",
    textAlign: "right",
    margin: "10px",
    bottom: "0",
    right: "0",
  },
  actions_tree_view: {
    borderBottomLeftRadius: "0",
    borderBottomRightRadius: "0",
  },
  actions_i: {
    backgroundSize: "contain",
    display: "inline-block",
    height: "15px",
    width: "15px",
    verticalAlign: "-0.25em",
  },
  actions_i_indent: { backgroundImage: "url(images/icons/indent.svg)" },
  actions_i_outdent: { backgroundImage: "url(images/icons/outdent.svg)" },
  actions_i_lock: { backgroundImage: "url(images/icons/lock-fill.svg)" },
  actions_i_image: { backgroundImage: "url(images/icons/file-image.svg)" },
  actions_i_table: { backgroundImage: "url(images/icons/table.svg)" },
  actions_i_unlock: { backgroundImage: "url(images/icons/lock.svg)" },
  actions_i_left_align: { backgroundImage: "url(images/icons/text-left.svg)" },
  actions_i_center_align: {
    backgroundImage: "url(images/icons/text-center.svg)",
  },
  actions_i_right_align: {
    backgroundImage: "url(images/icons/text-right.svg)",
  },
  actions_i_justify_align: { backgroundImage: "url(images/icons/justify.svg)" },
  actions_i_disconnect: { backgroundImage: "url(images/icons/plug.svg)" },
  actions_i_connect: { backgroundImage: "url(images/icons/plug-fill.svg)" },
  table_cell_action_button_container: {
    position: "absolute",
    top: "0",
    left: "0",
    willChange: "transform",
  },
  table_cell_action_button: {
    backgroundColor: "none",
    display: "inline-block",
    justifyContent: "center",
    alignItems: "center",
    border: "0",
    position: "relative",
    borderRadius: "15px",
    color: "#222",
    cursor: "pointer",
  },
  i_chevron_down: {
    backgroundColor: "transparent",
    backgroundSize: "contain",
    display: "inline-block",
    height: "8px",
    width: "8px",
    backgroundImage: "url(images/icons/chevron-down.svg)",
  },
  action_button: {
    backgroundColor: "#eee",
    border: "0",
    padding: "8px 12px",
    position: "relative",
    marginLeft: "5px",
    borderRadius: "15px",
    color: "#222",
    display: "inline-block",
    cursor: "pointer",
  },
  action_button_hover: { backgroundColor: "#ddd", color: "#000" },
  action_button_mic_active: { animation: "mic-pulsate-color 3s infinite" },
  button_action_button_disabled: {
    opacity: "0.6",
    background: "#eee",
    cursor: "not-allowed",
  },
  debug_timetravel_panel: {
    overflow: "hidden",
    padding: "0 0 10px 0",
    margin: "auto",
    display: "flex",
  },
  debug_timetravel_panel_slider: { padding: "0", flex: "8" },
  debug_timetravel_panel_button: {
    padding: "0",
    border: "0",
    background: "none",
    flex: "1",
    color: "#fff",
    fontSize: "12px",
  },
  debug_timetravel_panel_button_hover: { textDecoration: "underline" },
  debug_timetravel_button: {
    border: "0",
    padding: "0",
    fontSize: "12px",
    top: "10px",
    right: "15px",
    position: "absolute",
    background: "none",
    color: "#fff",
  },
  debug_timetravel_button_hover: { textDecoration: "underline" },
  debug_treetype_button: {
    border: "0",
    padding: "0",
    fontSize: "12px",
    top: "10px",
    right: "85px",
    position: "absolute",
    background: "none",
    color: "#fff",
  },
  debug_treetype_button_hover: { textDecoration: "underline" },
  connecting: {
    fontSize: "15px",
    color: "#999",
    overflow: "hidden",
    position: "absolute",
    textOverflow: "ellipsis",
    top: "10px",
    left: "10px",
    userSelect: "none",
    whiteSpace: "nowrap",
    display: "inline-block",
    pointerEvents: "none",
  },
  ltr: { textAlign: "left" },
  rtl: { textAlign: "right" },
  toolbar: {
    display: "flex",
    marginBottom: "1px",
    background: "#fff",
    padding: "4px",
    borderTopLeftRadius: "10px",
    borderTopRightRadius: "10px",
    verticalAlign: "middle",
    overflow: "auto",
    height: "36px",
    position: "sticky",
    top: "0",
    zIndex: "2",
  },
  button_toolbar_item: {
    border: "0",
    display: "flex",
    background: "none",
    borderRadius: "10px",
    padding: "8px",
    cursor: "pointer",
    verticalAlign: "middle",
    flexShrink: "0",
    alignItems: "center",
    justifyContent: "space-between",
  },
  button_toolbar_item_disabled: { cursor: "not-allowed" },
  button_toolbar_item_spaced: { marginRight: "2px" },
  button_toolbar_item_i_format: {
    backgroundSize: "contain",
    display: "flex",
    height: "18px",
    width: "18px",
    verticalAlign: "-0.25em",
    opacity: "0.6",
  },
  button_toolbar_item_disabled__icon: { opacity: "0.2" },
  button_toolbar_item_disabled__text: { opacity: "0.2" },
  button_toolbar_item_disabled_i_format: { opacity: "0.2" },
  button_toolbar_item_disabled__chevron_down: { opacity: "0.2" },
  button_toolbar_item_active: { backgroundColor: "rgba(223, 232, 250, 0.3)" },
  button_toolbar_item_active_i: { opacity: "1" },
  toolbar_item_hover_not__disabled: { backgroundColor: "#eee" },
  toolbar_item_font_family__text: { display: "block", maxWidth: "40px" },
  toolbar__code_language: { width: "150px" },
  toolbar__toolbar_item__text: {
    display: "flex",
    lineHeight: "20px",
    verticalAlign: "middle",
    fontSize: "14px",
    color: "#777",
    textOverflow: "ellipsis",
    overflow: "hidden",
    height: "20px",
    textAlign: "left",
    paddingRight: "10px",
  },
  toolbar__toolbar_item__icon: {
    display: "flex",
    width: "20px",
    height: "20px",
    userSelect: "none",
    marginRight: "8px",
    lineHeight: "16px",
    backgroundSize: "contain",
  },
  toolbar_i_chevron_down: {
    marginTop: "3px",
    width: "16px",
    height: "16px",
    display: "flex",
    userSelect: "none",
  },
  toolbar_item_i_chevron_down: {
    marginTop: "3px",
    width: "16px",
    height: "16px",
    display: "flex",
    userSelect: "none",
  },
  toolbar_i_chevron_down_inside: {
    width: "16px",
    height: "16px",
    display: "flex",
    marginLeft: "-25px",
    marginTop: "11px",
    marginRight: "10px",
    pointerEvents: "none",
  },
  toolbar__divider: { width: "1px", backgroundColor: "#eee", margin: "0 4px" },
  sticky_note_container: {
    position: "absolute",
    zIndex: "9",
    width: "120px",
    display: "inline-block",
  },
  sticky_note: {
    lineHeight: "1",
    textAlign: "left",
    width: "120px",
    margin: "25px",
    padding: "20px 10px",
    position: "relative",
    border: "1px solid #e8e8e8",
    fontFamily: "'Reenie Beanie'",
    fontSize: "24px",
    borderBottomRightRadius: "60px 5px",
    display: "block",
    cursor: "move",
  },
  sticky_note_after: {
    content: "''",
    position: "absolute",
    zIndex: "-1",
    right: "-0px",
    bottom: "20px",
    width: "120px",
    height: "25px",
    background: "rgba(0, 0, 0, 0.2)",
    boxShadow: "2px 15px 5px rgba(0, 0, 0, 0.4)",
    transform: "matrix(-1, -0.1, 0, 1, 0, 0)",
  },
  sticky_note_yellow: {
    borderTop: "1px solid #fdfd86",
    background:
      "linear-gradient(\n    135deg,\n    #ffff88 81%,\n    #ffff88 82%,\n    #ffff88 82%,\n    #ffffc6 100%\n  )",
  },
  sticky_note_pink: {
    borderTop: "1px solid #e7d1e4",
    background:
      "linear-gradient(\n    135deg,\n    #f7cbe8 81%,\n    #f7cbe8 82%,\n    #f7cbe8 82%,\n    #e7bfe1 100%\n  )",
  },
  sticky_note_container_dragging: { transition: "none !important" },
  sticky_note_div: { cursor: "text" },
  sticky_note__delete: {
    border: "0",
    background: "none",
    position: "absolute",
    top: "8px",
    right: "10px",
    fontSize: "10px",
    cursor: "pointer",
    opacity: "0.5",
  },
  sticky_note__delete_hover: { fontWeight: "bold", opacity: "1" },
  sticky_note__color: {
    border: "0",
    background: "none",
    position: "absolute",
    top: "8px",
    right: "25px",
    cursor: "pointer",
    opacity: "0.5",
  },
  sticky_note__color_hover: { opacity: "1" },
  sticky_note__color_i: {
    display: "block",
    width: "12px",
    height: "12px",
    backgroundSize: "contain",
  },
  excalidraw_button: {
    border: "0",
    padding: "0",
    margin: "0",
    backgroundColor: "transparent",
  },
  excalidraw_button_selected: {
    outline: "2px solid rgb(60, 132, 244)",
    userSelect: "none",
  },
  github_corner_hover__octo_arm: {
    animation: "octocat-wave 560ms ease-in-out",
  },
  "@media (max-width: 500px)": {
    __expression__: "(max-width: 500px)",
    github_corner_hover__octo_arm: { animation: "none" },
    github_corner__octo_arm: { animation: "octocat-wave 560ms ease-in-out" },
  },
  spacer: { letterSpacing: "-2px" },
  editor_equation: { cursor: "default", userSelect: "none" },
  editor_equation_focused: { outline: "2px solid rgb(60, 132, 244)" },
  button_item_i: { opacity: "0.6" },
  button_item_dropdown_item_active: {
    backgroundColor: "rgba(223, 232, 250, 0.3)",
  },
  button_item_dropdown_item_active_i: { opacity: "1" },
  hr: {
    padding: "2px 2px",
    border: "none",
    margin: "1em 0",
    cursor: "pointer",
  },
  hr_after: {
    content: "''",
    display: "block",
    height: "2px",
    backgroundColor: "#ccc",
    lineHeight: "2px",
  },
  hr_selected: { outline: "2px solid rgb(60, 132, 244)", userSelect: "none" },
  TableNode__contentEditable: {
    minHeight: "20px",
    border: "0px",
    resize: "none",
    cursor: "text",
    display: "block",
    position: "relative",
    outline: "0px",
    padding: "0",
    userSelect: "text",
    fontSize: "15px",
    whiteSpace: "pre-wrap",
    wordBreak: "break-word",
    zIndex: "3",
  },
  PlaygroundEditorTheme__blockCursor: {
    display: "block",
    pointerEvents: "none",
    position: "absolute",
  },
  PlaygroundEditorTheme__blockCursor_after: {
    content: "''",
    display: "block",
    position: "absolute",
    top: "-2px",
    width: "20px",
    borderTop: "1px solid black",
    animation: "CursorBlink 1.1s steps(2, start) infinite",
  },
  dialog_dropdown: {
    backgroundColor: "#eee !important",
    marginBottom: "10px",
    width: "100%",
    color: "black",
  },
  contenteditable: { outline: "0px solid transparent" },
  Button__root: {
    paddingTop: "10px",
    paddingBottom: "10px",
    paddingLeft: "15px",
    paddingRight: "15px",
    border: "0px",
    backgroundColor: "#eee",
    borderRadius: "5px",
    cursor: "pointer",
    fontSize: "14px",
  },
  Button__root_hover: { backgroundColor: "#ddd" },
  Button__small: {
    paddingTop: "5px",
    paddingBottom: "5px",
    paddingLeft: "10px",
    paddingRight: "10px",
    fontSize: "13px",
  },
  Button__disabled: { cursor: "not-allowed" },
  Button__disabled_hover: { backgroundColor: "#eee" },
  type__checkbox___checked: { position: "absolute", left: "-9999px" },
  type__checkbox___not__checked: { position: "absolute", left: "-9999px" },
  type__checkbox___checked___label: {
    position: "relative",
    paddingRight: "55px",
    cursor: "pointer",
    lineHeight: "20px",
    display: "inline-block",
    color: "#666",
  },
  type__checkbox___not__checked____label: {
    position: "relative",
    paddingRight: "55px",
    cursor: "pointer",
    lineHeight: "20px",
    display: "inline-block",
    color: "#666",
  },
  type__checkbox___checked___label_before: {
    content: "''",
    position: "absolute",
    right: "0",
    top: "0",
    width: "18px",
    height: "18px",
    border: "1px solid #666",
    background: "#fff",
  },
  type__checkbox___not__checked____label_before: {
    content: "''",
    position: "absolute",
    right: "0",
    top: "0",
    width: "18px",
    height: "18px",
    border: "1px solid #666",
    background: "#fff",
  },
  type__checkbox___checked___label_after: {
    opacity: "1",
    WebkitTransform: "scale(1)",
    transform: "scale(1)",
  },
  type__checkbox___not__checked____label_after: {
    opacity: "0",
    WebkitTransform: "scale(0)",
    transform: "scale(0)",
  },
  color_picker_wrapper: { padding: "20px" },
  color_picker_basic_color: {
    display: "flex",
    flexWrap: "wrap",
    gap: "10px",
    margin: "0",
    padding: "0",
  },
  color_picker_basic_color_button: {
    border: "1px solid #ccc",
    borderRadius: "4px",
    height: "16px",
    width: "16px",
    cursor: "pointer",
    listStyleType: "none",
  },
  color_picker_basic_color_button_active: {
    boxShadow: "0px 0px 2px 2px rgba(0, 0, 0, 0.3)",
  },
  color_picker_saturation: {
    width: "100%",
    position: "relative",
    marginTop: "15px",
    height: "150px",
    backgroundImage:
      "linear-gradient(transparent, black),\n    linear-gradient(to right, white, transparent)",
    userSelect: "none",
  },
  color_picker_saturation_cursor: {
    position: "absolute",
    width: "20px",
    height: "20px",
    border: "2px solid #ffffff",
    borderRadius: "50%",
    boxShadow: "0 0 15px #00000026",
    boxSizing: "border-box",
    transform: "translate(-10px, -10px)",
  },
  color_picker_hue: {
    width: "100%",
    position: "relative",
    marginTop: "15px",
    height: "12px",
    backgroundImage:
      "linear-gradient(\n    to right,\n    rgb(255, 0, 0),\n    rgb(255, 255, 0),\n    rgb(0, 255, 0),\n    rgb(0, 255, 255),\n    rgb(0, 0, 255),\n    rgb(255, 0, 255),\n    rgb(255, 0, 0)\n  )",
    userSelect: "none",
    borderRadius: "12px",
  },
  color_picker_hue_cursor: {
    position: "absolute",
    width: "20px",
    height: "20px",
    border: "2px solid #ffffff",
    borderRadius: "50%",
    boxShadow: "#0003 0 0 0 0.5px",
    boxSizing: "border-box",
    transform: "translate(-10px, -4px)",
  },
  color_picker_color: {
    border: "1px solid #ccc",
    marginTop: "15px",
    width: "100%",
    height: "20px",
  },
  ContentEditable__root: {
    border: "0",
    fontSize: "15px",
    display: "block",
    position: "relative",
    outline: "0",
    padding: "8px 28px 40px",
    minHeight: "150px",
  },
  "@media (max-width: 1025px)": {
    __expression__: "(max-width: 1025px)",
    ContentEditable__root: { paddingLeft: "8px", paddingRight: "8px" },

    Placeholder__root: { left: "8px" },
  },
  DialogActions: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "right",
    marginTop: "20px",
  },
  DialogButtonsList: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "right",
    marginTop: "20px",
  },
  DialogButtonsList_button: { marginBottom: "20px" },
  EquationEditor_inlineEditor: {
    padding: "0",
    margin: "0",
    border: "0",
    outline: "0",
    color: "#8421a2",
    backgroundColor: "inherit",
    resize: "none",
  },
  EquationEditor_blockEditor: {
    padding: "0",
    margin: "0",
    border: "0",
    outline: "0",
    color: "#8421a2",
    backgroundColor: "inherit",
    resize: "none",
    width: "100%",
  },
  EquationEditor_inputBackground: { backgroundColor: "#eee" },
  EquationEditor_dollarSign: { textAlign: "left", color: "#b0b0b0" },
  Input__wrapper: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    marginBottom: "10px",
  },
  Input__label: { display: "flex", flex: "1", color: "#666" },
  Input__input: {
    display: "flex",
    flex: "2",
    border: "1px solid #999",
    paddingTop: "7px",
    paddingBottom: "7px",
    paddingLeft: "10px",
    paddingRight: "10px",
    fontSize: "16px",
    borderRadius: "5px",
    minWidth: "0",
    color: "black",
  },
  KatexEquationAlterer_defaultRow: {
    display: "flex",
    flexDirection: "row",
    marginTop: "10px",
    marginBottom: "10px",
    justifyContent: "space-between",
    overflow: "hidden",
    color: "black",
  },
  KatexEquationAlterer_dialogActions: {
    display: "flex",
    flexDirection: "row",
    overflow: "hidden",
    marginTop: "20px",
    marginBottom: "0",
    justifyContent: "right",
  },
  KatexEquationAlterer_centerRow: {
    display: "flex",
    flexDirection: "'row'",
    marginTop: "10px",
    marginBottom: "10px",
    justifyContent: "center",
    overflow: "hidden",
  },
  KatexEquationAlterer_textArea: {
    width: "100%",
    resize: "none",
    padding: "7px",
    border: "grey",
  },
  Modal__overlay: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    position: "fixed",
    flexDirection: "column",
    top: "0px",
    bottom: "0px",
    left: "0px",
    right: "0px",
    backgroundColor: "rgba(40, 40, 40, 0.6)",
    flexGrow: "0px",
    flexShrink: "1px",
    zIndex: "100",
  },
  Modal__modal: {
    padding: "20px",
    minHeight: "100px",
    minWidth: "300px",
    display: "flex",
    flexGrow: "0px",
    backgroundColor: "#fff",
    flexDirection: "column",
    position: "relative",
    boxShadow: "0 0 20px 0 #444",
    borderRadius: "10px",
  },
  Modal__title: {
    color: "#444",
    margin: "0px",
    paddingBottom: "10px",
    borderBottom: "1px solid #ccc",
  },
  Modal__closeButton: {
    border: "0px",
    position: "absolute",
    right: "20px",
    borderRadius: "20px",
    justifyContent: "center",
    alignItems: "center",
    display: "flex",
    width: "30px",
    height: "30px",
    textAlign: "center",
    cursor: "pointer",
    backgroundColor: "rgb(79 70 229)",
  },
  Modal__closeButton_hover: { backgroundColor: "rgba(78, 70, 229, 0.644)" },
  Modal__content: { paddingTop: "20px" },
  Placeholder__root: {
    fontSize: "15px",
    color: "#999",
    overflow: "hidden",
    position: "absolute",
    textOverflow: "ellipsis",
    top: "4.4rem",
    left: "4rem",
    right: "4rem",
    userSelect: "none",
    whiteSpace: "nowrap",
    display: "inline-block",
    pointerEvents: "none",
  },

  select: {
    minWidth: "160px",
    maxWidth: "290px",
    border: "1px solid var(--select-border)",
    borderRadius: "0.25em",
    padding: "0.25em 0.5em",
    fontSize: "1rem",
    cursor: "pointer",
    lineHeight: "1.4",
    background: "linear-gradient(to bottom, #ffffff 0%, #e5e5e5 100%)",
  },
  root: {
    "-selectBorder": "#393939",
    "-selectFocus": "#101484",
    "-selectArrow": "var(--select-border)",
  },
  CommentEditorTheme__paragraph: { margin: "0", position: "'relative'" },
};
