
import WebAppHeader from "@/components/WebAppIndexComponents/WebAppHeader/header";
import type { Metadata } from "next";
import { Inter } from "next/font/google";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function WebappLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <main className="min-h-screen ">
      <WebAppHeader />
      {children}
    </main>
  );
}
