export { ClinicalEventRelationsResolver } from "./ClinicalEvent/ClinicalEventRelationsResolver";
export { ConsultationRelationsResolver } from "./Consultation/ConsultationRelationsResolver";
export { ConsultationListRelationsResolver } from "./ConsultationList/ConsultationListRelationsResolver";
export { DocumentStoreRelationsResolver } from "./DocumentStore/DocumentStoreRelationsResolver";
export { ModalityRelationsResolver } from "./Modality/ModalityRelationsResolver";
export { PatientRelationsResolver } from "./Patient/PatientRelationsResolver";
export { PrescriptionRelationsResolver } from "./Prescription/PrescriptionRelationsResolver";
export { UserRelationsResolver } from "./User/UserRelationsResolver";
export { WorkingListRelationsResolver } from "./WorkingList/WorkingListRelationsResolver";
