export * from './Patients'
export * from './ConsultationList'
export * from './MobileDevices'
export * from './Global'
export * from './ClinicalEvents'
export * from './ClinicalDiagnostics'
export * from './Drugs'
