import AdminPanelSell from "@/components/AdminPanelComponents/AdminPanelSell";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Administration panel",
  description: "Generated by create next app",
};

export default function WebappLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <main className="min-h-screen ">
      {children}
      {/* <AdminPanelSell>{children}</AdminPanelSell> */}
    </main>
  );
}
