[http]
[http.routers]
[http.routers.dgraph-route]
entryPoints = ["web"]
rule = "Host(`dgraph.bolt3.local`)"
service = "dgraph"

[http.services]
[http.services.dgraph]
[http.services.dgraph.loadBalancer]
[[http.services.dgraph.loadBalancer.servers]]
url = "http://host.docker.internal:8087"
