[http]
[http.routers]
[http.routers.live-route]
entryPoints = ["web"]
rule = "Host(`live.bolt3.local`)"
service = "live"

[http.services]
[http.services.live]
[http.services.live.loadBalancer]
[[http.services.live.loadBalancer.servers]]
url = "http://host.docker.internal:5555"
