[http]
[http.routers]
[http.routers.pacs-route]
entryPoints = ["web"]
rule = "Host(`pacs.bolt3.local`)"
service = "pacs"

[http.services]
[http.services.pacs]
[http.services.pacs.loadBalancer]
[[http.services.pacs.loadBalancer.servers]]
url = "http://100.74.3.18:8042"
