[http]
[http.routers]
[http.routers.wundergraph-route]
entryPoints = ["web"]
service = "wundergraph"
rule = "Host(`api.bolt3.local`)"

[http.services]
[http.services.wundergraph]
[http.services.wundergraph.loadBalancer]
[[http.services.wundergraph.loadBalancer.servers]]
url = "http://host.docker.internal:9991"
