import AdminPanelSell from "@/components/AdminPanelComponents/AdminPanelSell";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Administration panel",
  description: "Generated by create next app",
};

export default function WebappLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <main className="min-h-screen ">
      <AdminPanelSell>{children}</AdminPanelSell>
    </main>
  );
}
